title: The Gippy Pages
email: shawn@topfroggraphics.com
author: Shawn Parker
description: >-
  The Gippy Pages is the brain dump of Shawn Parker on the internet. 
  Covering topics ranging from how my butt itches to software development. 
  Your mileage may vary. Not suitable for all ages. This site contains 
  content known by the State of California to cause cancer.
baseurl: ""
url: "https://top-frog.com"
permalink: /:year/:month/:day/:title:output_ext
encoding: utf-8
lang: en-US
timezone: America/Los_Angeles
twitter:
  username: wookieeboy
  card: summary
logo: /assets/big-frog.optimized.svg
social:
  name: Shawn Parker
  links:
    - https://twitter.com/WookieeBoy
    - https://www.linkedin.com/in/ShawnParker
    - https://www.flickr.com/photos/tehgipster
    - https://github.com/Gipetto
markdown: kramdown
sass:
  style: compressed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"] # note the spaces, this preserves conditional comments
  startings: []
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: ['local']
theme: minima # Build on top of the Minima theme functionality
excerpt_separator: <!--more-->
feed:
  path: feed
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-twitter-plugin
kramdown:
  input: GFM
  syntax-highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
include:
#  - .htaccess
exclude:
  - _drafts
  - _bin
  - Gemfile
  - Gemfile.lock
  - Makefile
  - node_modules
  - ReadMe.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
