title: The Gippy Pages
email: shawn@topfroggraphics.com
description: >-
  The Gippy Pages is the brain dump of Shawn Parker on the internet. 
  Covering topics ranging from how my butt itches to software development. 
  Your mileage may vary. Not suitable for all ages. This site contains 
  content known by the State of California to cause cancer.
baseurl: ""
url: "https://top-frog.com"
encoding: utf-8
timezone: America/Los_Angeles
# Build settings
markdown: kramdown
theme: minima
paginate: 5
paginate_path: /:num/
excerpt_separator: <!--more-->
feed:
  path: feed
plugins:
#  - jekyll-seo-tag
#  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-twitter-plugin
kramdown:
  input: GFM
  syntax-highlighter: rouge
# Exclude from processing.
exclude:
  - _drafts
  - Gemfile
  - Gemfile.lock
  - Makefile
  - node_modules
  - ReadMe.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
